In [3]:
import numpy as np

In [9]:
myarr = np.array([[1,2,6],[3,4,5]],np.int64)

In [15]:
myarr[0,2]

np.int64(7)

In [10]:
myarr.shape

(2, 3)

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr[0,2] = 7

In [16]:
myarr

array([[1, 2, 7],
       [3, 4, 5]])

In [18]:
zeroes = np.zeros((2,5))

In [19]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
rng  = np.arange(10)

In [23]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
lspace = np.linspace(1,50,10)

In [27]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
emp = np.empty((4,6))

In [29]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
ide = np.identity(10)

In [31]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [42]:
arr = np.arange(100)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
arr.shape

(100,)

In [49]:
arr = arr.reshape(20,5)

In [50]:
arr.shape

(20, 5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [52]:
arr = arr.ravel()

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [54]:
arrAxis = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
arrAxis

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arrAxis.sum(axis=0)

array([12, 15, 18])

In [57]:
arrAxis.sum(axis=1)

array([ 6, 15, 24])

In [58]:
arrAxis.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
arrAxis.ndim

2

In [60]:
arrAxis.nbytes

72

In [61]:
arrAxis.argmax()

np.int64(8)

In [62]:
arrAxis.argmin()

np.int64(0)

In [63]:
arrAxis.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [64]:
arrSort = np.array([[87,34,12],[54,23,54],[65,25,84]])

In [66]:
arrSort

array([[87, 34, 12],
       [54, 23, 54],
       [65, 25, 84]])

In [67]:
arrSort.argmax(axis=0)

array([0, 0, 2])

In [69]:
arrSort.argmin(axis=1)

array([2, 1, 1])

In [70]:
arrSort + arrAxis

array([[88, 36, 15],
       [58, 28, 60],
       [72, 33, 93]])

In [71]:
arrSort * arrAxis

array([[ 87,  68,  36],
       [216, 115, 324],
       [455, 200, 756]])

In [72]:
np.sqrt(arrSort)

array([[9.32737905, 5.83095189, 3.46410162],
       [7.34846923, 4.79583152, 7.34846923],
       [8.06225775, 5.        , 9.16515139]])

In [73]:
arrSort.sum()

np.int64(438)

In [74]:
arrSort.min()

np.int64(12)

In [75]:
arrSort.max()

np.int64(87)

In [76]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)

In [77]:
sys.getsizeof(1)*len(py_ar)

112

In [78]:
np_ar.itemsize*np_ar.size

32